-- @generated by mysqldump from the V1-V33 schema; do not edit manually.
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `sys_login_token` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `token` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'JWT摘要，兼容升级期间的旧值长度',
  `device_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `login_ip` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `expire_time` datetime(3) NOT NULL,
  `created_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_login_token_token` (`token`),
  KEY `idx_login_token_user` (`user_id`),
  KEY `idx_login_token_expire` (`expire_time`),
  CONSTRAINT `fk_login_token_user` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `sys_notification_channel` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '渠道类型: dingtalk, feishu, bark, webhook, email, wxwork, telegram, pushplus',
  `name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '通知名称',
  `config` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '配置参数(JSON)',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态: 0-关闭, 1-开启',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='通知渠道表';
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `sys_user` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `username` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` tinyint NOT NULL DEFAULT '1',
  `last_login_time` datetime(3) DEFAULT NULL,
  `last_login_ip` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_user_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_account` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `account_note` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unb` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `avatar_url` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '闲鱼账号头像地址（可获取时缓存）',
  `device_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` tinyint NOT NULL DEFAULT '1',
  `created_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `auto_rate_enabled` int DEFAULT '0',
  `auto_rate_text` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `auto_ask_flower` tinyint(1) DEFAULT '0' COMMENT '发货后是否求小红花 1:是 0:否',
  `auto_ask_flower_text` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '求小红花文案',
  `auto_connect_on_startup` tinyint NOT NULL DEFAULT '1' COMMENT '服务器启动后自动恢复 WebSocket：1-开启，0-关闭',
  `automation_risk_paused` tinyint NOT NULL DEFAULT '0',
  `automation_risk_pause_reason` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `automation_risk_paused_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_account_unb` (`unb`),
  KEY `idx_account_status` (`status`),
  KEY `idx_account_automation_risk_paused` (`automation_risk_paused`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_ai_bargain_session` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `xianyu_account_id` bigint NOT NULL,
  `xy_goods_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `buyer_user_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `s_id` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `current_offer` decimal(12,2) DEFAULT NULL,
  `bargain_round` int NOT NULL DEFAULT '0',
  `reached_floor` tinyint NOT NULL DEFAULT '0',
  `last_buyer_message` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bargain_account_goods_buyer` (`xianyu_account_id`,`xy_goods_id`,`buyer_user_id`),
  KEY `idx_bargain_updated` (`updated_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_api_kami_delivery` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `kami_config_id` bigint NOT NULL,
  `xianyu_account_id` bigint NOT NULL,
  `order_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `delivery_content` text COLLATE utf8mb4_unicode_ci,
  `request_token` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `state` tinyint NOT NULL DEFAULT '0' COMMENT '0请求中 1已获取 2请求失败',
  `error_message` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `request_time` datetime(3) DEFAULT NULL,
  `response_time` datetime(3) DEFAULT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_api_kami_config_account_order` (`kami_config_id`,`xianyu_account_id`,`order_id`),
  KEY `idx_api_kami_order` (`xianyu_account_id`,`order_id`),
  CONSTRAINT `fk_api_kami_delivery_account` FOREIGN KEY (`xianyu_account_id`) REFERENCES `xianyu_account` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_api_kami_delivery_config` FOREIGN KEY (`kami_config_id`) REFERENCES `xianyu_kami_config` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_buyer_blacklist` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `xianyu_account_id` bigint DEFAULT NULL COMMENT 'NULL 表示所有账号',
  `account_scope` bigint GENERATED ALWAYS AS (coalesce(`xianyu_account_id`,0)) STORED,
  `buyer_user_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `buyer_user_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reason` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `enabled` tinyint NOT NULL DEFAULT '1',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_buyer_blacklist_scope` (`account_scope`,`buyer_user_id`),
  KEY `idx_buyer_blacklist_lookup` (`buyer_user_id`,`enabled`,`account_scope`),
  KEY `fk_buyer_blacklist_account` (`xianyu_account_id`),
  CONSTRAINT `fk_buyer_blacklist_account` FOREIGN KEY (`xianyu_account_id`) REFERENCES `xianyu_account` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_chat_buyer_tag` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `xianyu_account_id` bigint NOT NULL,
  `buyer_user_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tag_name` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_chat_buyer_tag` (`xianyu_account_id`,`buyer_user_id`,`tag_name`),
  KEY `idx_chat_buyer_tag_lookup` (`xianyu_account_id`,`buyer_user_id`),
  CONSTRAINT `fk_chat_buyer_tag_account` FOREIGN KEY (`xianyu_account_id`) REFERENCES `xianyu_account` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_chat_message` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `xianyu_account_id` bigint NOT NULL,
  `lwp` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pnm_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `s_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `content_type` int DEFAULT NULL,
  `msg_content` text COLLATE utf8mb4_unicode_ci,
  `sender_user_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sender_user_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sender_app_v` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sender_os_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reminder_url` text COLLATE utf8mb4_unicode_ci,
  `xy_goods_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `complete_msg` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `message_time` bigint DEFAULT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_chat_message_account_pnm` (`xianyu_account_id`,`pnm_id`),
  KEY `idx_chat_account_session_time` (`xianyu_account_id`,`s_id`,`message_time`),
  KEY `idx_chat_sender` (`sender_user_id`),
  KEY `idx_chat_goods` (`xianyu_account_id`,`xy_goods_id`),
  KEY `idx_chat_account_session_id` (`xianyu_account_id`,`s_id`,`id`),
  CONSTRAINT `fk_chat_account` FOREIGN KEY (`xianyu_account_id`) REFERENCES `xianyu_account` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_chat_session_read` (
  `xianyu_account_id` bigint NOT NULL,
  `s_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_read_message_id` bigint NOT NULL DEFAULT '0',
  `last_read_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`xianyu_account_id`,`s_id`),
  CONSTRAINT `fk_chat_session_read_account` FOREIGN KEY (`xianyu_account_id`) REFERENCES `xianyu_account` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_chat_user_profile` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `xianyu_account_id` bigint NOT NULL,
  `s_id` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `buyer_user_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `buyer_user_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `avatar_url` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `expires_at` datetime(3) NOT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_chat_profile_account_session` (`xianyu_account_id`,`s_id`),
  KEY `idx_chat_profile_expire` (`expires_at`),
  KEY `idx_chat_profile_buyer` (`xianyu_account_id`,`buyer_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_cookie` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `xianyu_account_id` bigint NOT NULL,
  `cookie_text` text COLLATE utf8mb4_unicode_ci,
  `m_h5_tk` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cookie_status` tinyint NOT NULL DEFAULT '1',
  `expire_time` datetime(3) DEFAULT NULL,
  `websocket_token` text COLLATE utf8mb4_unicode_ci,
  `token_expire_time` bigint DEFAULT NULL,
  `created_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cookie_account` (`xianyu_account_id`),
  KEY `idx_cookie_status` (`cookie_status`),
  KEY `idx_cookie_token_expire` (`token_expire_time`),
  CONSTRAINT `fk_cookie_account` FOREIGN KEY (`xianyu_account_id`) REFERENCES `xianyu_account` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_goods` (
  `id` bigint NOT NULL,
  `xy_good_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `xianyu_account_id` bigint DEFAULT NULL,
  `title` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cover_pic` text COLLATE utf8mb4_unicode_ci,
  `info_pic` text COLLATE utf8mb4_unicode_ci,
  `detail_info` longtext COLLATE utf8mb4_unicode_ci,
  `detail_url` text COLLATE utf8mb4_unicode_ci,
  `sold_price` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sku_count` int NOT NULL DEFAULT '0',
  `status` tinyint NOT NULL DEFAULT '0',
  `created_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_goods_account_remote` (`xianyu_account_id`,`xy_good_id`),
  KEY `idx_goods_remote` (`xy_good_id`),
  KEY `idx_goods_account_status` (`xianyu_account_id`,`status`),
  CONSTRAINT `fk_goods_account` FOREIGN KEY (`xianyu_account_id`) REFERENCES `xianyu_account` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_goods_auto_delivery_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `xianyu_account_id` bigint NOT NULL,
  `xianyu_goods_id` bigint DEFAULT NULL,
  `xy_goods_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `delivery_mode` tinyint NOT NULL DEFAULT '1',
  `sku_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sku_key` varchar(32) COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (coalesce(`sku_id`,_utf8mb4'')) STORED,
  `sku_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `auto_delivery_content` text COLLATE utf8mb4_unicode_ci,
  `kami_config_ids` text COLLATE utf8mb4_unicode_ci,
  `kami_delivery_template` text COLLATE utf8mb4_unicode_ci,
  `auto_delivery_image_url` text COLLATE utf8mb4_unicode_ci,
  `auto_confirm_shipment` tinyint NOT NULL DEFAULT '0',
  `rag_delay_seconds` int NOT NULL DEFAULT '15',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `auto_ask_flower` int DEFAULT '0',
  `auto_ask_flower_text` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_delivery_config_account_goods_sku` (`xianyu_account_id`,`xy_goods_id`,`sku_key`),
  KEY `idx_delivery_config_goods` (`xianyu_goods_id`),
  CONSTRAINT `fk_delivery_config_account` FOREIGN KEY (`xianyu_account_id`) REFERENCES `xianyu_account` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_goods_auto_reply_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `xianyu_account_id` bigint NOT NULL,
  `xianyu_goods_id` bigint DEFAULT NULL,
  `xy_goods_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `s_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pnm_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `buyer_user_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `buyer_user_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `buyer_message` text COLLATE utf8mb4_unicode_ci,
  `reply_content` text COLLATE utf8mb4_unicode_ci,
  `reply_type` tinyint NOT NULL DEFAULT '1',
  `dedup_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `matched_keyword` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `trigger_context` longtext COLLATE utf8mb4_unicode_ci,
  `state` tinyint NOT NULL DEFAULT '0',
  `scheduled_time` datetime(3) DEFAULT NULL,
  `attempt_count` int NOT NULL DEFAULT '0',
  `next_retry_time` datetime(3) DEFAULT NULL,
  `lease_owner` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lease_expire_time` datetime(3) DEFAULT NULL,
  `last_error_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_error_message` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_reply_account_session_message` (`xianyu_account_id`,`s_id`,`pnm_id`),
  UNIQUE KEY `uk_reply_dedup_key` (`dedup_key`),
  KEY `idx_reply_due` (`state`,`scheduled_time`,`next_retry_time`,`lease_expire_time`),
  KEY `idx_reply_account_goods_created` (`xianyu_account_id`,`xy_goods_id`,`create_time`),
  CONSTRAINT `fk_reply_account` FOREIGN KEY (`xianyu_account_id`) REFERENCES `xianyu_account` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_goods_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `xianyu_account_id` bigint NOT NULL,
  `xianyu_goods_id` bigint DEFAULT NULL,
  `xy_goods_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `xianyu_auto_delivery_on` tinyint NOT NULL DEFAULT '0',
  `xianyu_auto_reply_on` tinyint NOT NULL DEFAULT '0',
  `xianyu_auto_reply_context_on` tinyint NOT NULL DEFAULT '1',
  `xianyu_keyword_reply_on` tinyint NOT NULL DEFAULT '0',
  `product_default_reply_on` tinyint NOT NULL DEFAULT '0',
  `product_default_reply_mode` tinyint NOT NULL DEFAULT '1',
  `product_default_reply_text` text COLLATE utf8mb4_unicode_ci,
  `product_default_reply_image_url` text COLLATE utf8mb4_unicode_ci,
  `human_intervention_on` tinyint NOT NULL DEFAULT '0',
  `human_intervention_minutes` int NOT NULL DEFAULT '10',
  `fixed_material` text COLLATE utf8mb4_unicode_ci,
  `ai_prompt` text COLLATE utf8mb4_unicode_ci COMMENT '商品专属 AI 回复规则',
  `ai_bargain_on` tinyint NOT NULL DEFAULT '0' COMMENT '商品 AI 议价开关',
  `ai_bargain_floor_price` decimal(12,2) DEFAULT NULL COMMENT 'AI 议价最低可接受价格',
  `ai_bargain_step_amount` decimal(12,2) DEFAULT NULL COMMENT '每轮最大让价金额',
  `ai_bargain_max_rounds` int NOT NULL DEFAULT '3' COMMENT '最大议价轮数',
  `ai_bargain_style` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'BALANCED' COMMENT '议价风格 FIRM/BALANCED/CLOSE',
  `ai_bargain_floor_reply` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '到达底价后的固定回复',
  `ai_bargain_instructions` text COLLATE utf8mb4_unicode_ci COMMENT '商品议价补充规则',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_goods_config_account_goods` (`xianyu_account_id`,`xy_goods_id`),
  KEY `idx_goods_config_local_goods` (`xianyu_goods_id`),
  CONSTRAINT `fk_goods_config_account` FOREIGN KEY (`xianyu_account_id`) REFERENCES `xianyu_account` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_goods_order` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `xianyu_account_id` bigint NOT NULL,
  `xianyu_goods_id` bigint DEFAULT NULL,
  `xy_goods_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `pnm_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `order_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `buyer_user_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `buyer_user_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sid` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `content` text COLLATE utf8mb4_unicode_ci,
  `state` tinyint NOT NULL DEFAULT '0',
  `fail_reason` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `confirm_state` tinyint NOT NULL DEFAULT '0',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `goods_title` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sku_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sku_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `order_create_time` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pay_success_time` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `consign_time` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `total_price` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `buy_num` int NOT NULL DEFAULT '1',
  `delivery_status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING',
  `expected_quantity` int NOT NULL DEFAULT '1',
  `delivered_quantity` int NOT NULL DEFAULT '0',
  `attempt_count` int NOT NULL DEFAULT '0',
  `next_retry_time` datetime(3) DEFAULT NULL,
  `lease_owner` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lease_expire_time` datetime(3) DEFAULT NULL,
  `delivery_channel` varchar(24) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `trade_status` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `trade_status_text` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_error_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_error_message` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `notification_status` tinyint NOT NULL DEFAULT '2',
  `confirm_task_status` varchar(24) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `confirm_attempt_count` int NOT NULL DEFAULT '0',
  `confirm_next_retry_time` datetime(3) DEFAULT NULL,
  `confirm_lease_owner` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `confirm_lease_expire_time` datetime(3) DEFAULT NULL,
  `confirm_error` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_goods_order_account_message` (`xianyu_account_id`,`pnm_id`),
  UNIQUE KEY `uk_goods_order_account_order` (`xianyu_account_id`,`order_id`),
  KEY `idx_goods_order_task` (`delivery_status`,`next_retry_time`,`lease_expire_time`),
  KEY `idx_goods_order_account_created` (`xianyu_account_id`,`create_time`),
  KEY `idx_goods_order_goods` (`xianyu_account_id`,`xy_goods_id`),
  KEY `idx_goods_order_state` (`state`,`confirm_state`),
  KEY `idx_goods_order_trade_status` (`xianyu_account_id`,`trade_status`),
  KEY `idx_confirm_task_due` (`confirm_task_status`,`confirm_next_retry_time`),
  KEY `idx_confirm_task_lease` (`confirm_task_status`,`confirm_lease_expire_time`),
  KEY `idx_goods_order_account_sku` (`xianyu_account_id`,`xy_goods_id`,`sku_id`),
  CONSTRAINT `fk_goods_order_account` FOREIGN KEY (`xianyu_account_id`) REFERENCES `xianyu_account` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_goods_sku` (
  `id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `xy_goods_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sku_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sku_key` varchar(32) COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (coalesce(`sku_id`,_utf8mb4'')) STORED,
  `price` int DEFAULT NULL,
  `quantity` int NOT NULL DEFAULT '0',
  `property_text` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `property_id` int DEFAULT NULL,
  `value_id` int DEFAULT NULL,
  `value_text` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `display_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `property_sort_order` int NOT NULL DEFAULT '0',
  `value_sort_order` int NOT NULL DEFAULT '0',
  `features` text COLLATE utf8mb4_unicode_ci,
  `xianyu_account_id` bigint DEFAULT NULL,
  `created_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_goods_sku_account_remote` (`xianyu_account_id`,`xy_goods_id`,`sku_key`),
  KEY `idx_goods_sku_account` (`xianyu_account_id`),
  CONSTRAINT `fk_goods_sku_account` FOREIGN KEY (`xianyu_account_id`) REFERENCES `xianyu_account` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_goods_sku_property` (
  `id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `xy_goods_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `property_id` int NOT NULL,
  `property_text` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `property_sort_order` int NOT NULL DEFAULT '0',
  `value_id` int NOT NULL,
  `value_text` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `value_sort_order` int NOT NULL DEFAULT '0',
  `xianyu_account_id` bigint DEFAULT NULL,
  `created_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sku_property_account_value` (`xianyu_account_id`,`xy_goods_id`,`property_id`,`value_id`),
  KEY `idx_sku_property_account` (`xianyu_account_id`),
  CONSTRAINT `fk_sku_property_account` FOREIGN KEY (`xianyu_account_id`) REFERENCES `xianyu_account` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_human_intervention_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `xianyu_account_id` bigint NOT NULL,
  `xy_goods_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `s_id` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `end_time` datetime(3) NOT NULL,
  `created_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_intervention_account_session` (`xianyu_account_id`,`s_id`),
  KEY `idx_intervention_expire` (`end_time`),
  CONSTRAINT `fk_intervention_account` FOREIGN KEY (`xianyu_account_id`) REFERENCES `xianyu_account` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_item_polish_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `xianyu_account_id` bigint NOT NULL,
  `enabled` tinyint NOT NULL DEFAULT '0',
  `schedule_time` varchar(5) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '09:00',
  `last_scheduled_date` date DEFAULT NULL,
  `last_run_at` datetime(3) DEFAULT NULL,
  `last_run_total` int NOT NULL DEFAULT '0',
  `last_run_success` int NOT NULL DEFAULT '0',
  `last_run_failed` int NOT NULL DEFAULT '0',
  `last_run_message` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_item_polish_config_account` (`xianyu_account_id`),
  CONSTRAINT `fk_item_polish_config_account` FOREIGN KEY (`xianyu_account_id`) REFERENCES `xianyu_account` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_item_polish_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `xianyu_account_id` bigint NOT NULL,
  `xy_goods_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `goods_title` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `trigger_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `success` tinyint NOT NULL,
  `message` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `resolved_at` datetime(3) DEFAULT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_item_polish_record_account_time` (`xianyu_account_id`,`create_time`),
  KEY `idx_item_polish_exception` (`success`,`resolved_at`,`create_time`),
  CONSTRAINT `fk_item_polish_record_account` FOREIGN KEY (`xianyu_account_id`) REFERENCES `xianyu_account` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_kami_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `xianyu_account_id` bigint DEFAULT NULL COMMENT '历史创建账号ID（卡券库全局共享）',
  `alias_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source_type` tinyint NOT NULL DEFAULT '1' COMMENT '1本地库存 2外部API',
  `fixed_content` text COLLATE utf8mb4_unicode_ci,
  `delivery_template` text COLLATE utf8mb4_unicode_ci,
  `api_url` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `api_method` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'POST',
  `api_headers` text COLLATE utf8mb4_unicode_ci,
  `api_request_template` text COLLATE utf8mb4_unicode_ci,
  `api_result_path` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `api_timeout_seconds` int NOT NULL DEFAULT '10',
  `alert_enabled` tinyint NOT NULL DEFAULT '0',
  `alert_threshold_type` tinyint NOT NULL DEFAULT '1',
  `alert_threshold_value` int NOT NULL DEFAULT '10',
  `alert_email` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `alert_state` tinyint NOT NULL DEFAULT '0' COMMENT '库存预警状态：0正常，1已进入预警区间',
  `total_count` int NOT NULL DEFAULT '0',
  `used_count` int NOT NULL DEFAULT '0',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_kami_config_account` (`xianyu_account_id`),
  CONSTRAINT `fk_kami_config_account` FOREIGN KEY (`xianyu_account_id`) REFERENCES `xianyu_account` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_kami_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `kami_config_id` bigint NOT NULL,
  `kami_content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `content_hash` binary(32) GENERATED ALWAYS AS (unhex(sha2(`kami_content`,256))) STORED,
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '0可用 1已交付 2已预占 3待核对',
  `order_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reserved_time` datetime(3) DEFAULT NULL,
  `used_time` datetime(3) DEFAULT NULL,
  `sort_order` int NOT NULL DEFAULT '0',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_kami_config_content` (`kami_config_id`,`content_hash`),
  KEY `idx_kami_reserve` (`kami_config_id`,`status`,`sort_order`,`id`),
  KEY `idx_kami_order` (`order_id`,`status`),
  CONSTRAINT `fk_kami_item_config` FOREIGN KEY (`kami_config_id`) REFERENCES `xianyu_kami_config` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_kami_usage_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `kami_config_id` bigint NOT NULL,
  `kami_item_id` bigint DEFAULT NULL,
  `xianyu_account_id` bigint NOT NULL,
  `xy_goods_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `order_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `delivery_index` int NOT NULL DEFAULT '1',
  `delivery_status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'RESERVED',
  `buyer_user_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `buyer_user_name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kami_content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_usage_order_index` (`xianyu_account_id`,`order_id`,`delivery_index`),
  UNIQUE KEY `uk_usage_item_order` (`kami_item_id`,`order_id`),
  KEY `idx_usage_config_created` (`kami_config_id`,`create_time`),
  CONSTRAINT `fk_usage_account` FOREIGN KEY (`xianyu_account_id`) REFERENCES `xianyu_account` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_usage_config` FOREIGN KEY (`kami_config_id`) REFERENCES `xianyu_kami_config` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_usage_item` FOREIGN KEY (`kami_item_id`) REFERENCES `xianyu_kami_item` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_keyword_reply_content` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `rule_id` bigint NOT NULL,
  `reply_text` text COLLATE utf8mb4_unicode_ci,
  `reply_image_url` text COLLATE utf8mb4_unicode_ci,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_keyword_content_rule` (`rule_id`),
  CONSTRAINT `fk_keyword_content_rule` FOREIGN KEY (`rule_id`) REFERENCES `xianyu_keyword_reply_rule` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_keyword_reply_rule` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `xianyu_account_id` bigint NOT NULL,
  `xy_goods_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `keyword` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `keywords` text COLLATE utf8mb4_unicode_ci COMMENT '每行一个触发关键词',
  `match_mode` int NOT NULL DEFAULT '1',
  `is_fallback` int NOT NULL DEFAULT '0',
  `unique_keyword` varchar(200) COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (if((`is_fallback` = 1),_utf8mb4'__FALLBACK__',`keyword`)) STORED,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_keyword_rule` (`xianyu_account_id`,`xy_goods_id`,`unique_keyword`),
  KEY `idx_keyword_rule_match` (`xianyu_account_id`,`xy_goods_id`,`match_mode`,`is_fallback`),
  CONSTRAINT `fk_keyword_rule_account` FOREIGN KEY (`xianyu_account_id`) REFERENCES `xianyu_account` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_operation_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `xianyu_account_id` bigint DEFAULT NULL,
  `operation_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `operation_module` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `operation_desc` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `operation_status` tinyint DEFAULT NULL,
  `target_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `target_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `request_params` text COLLATE utf8mb4_unicode_ci,
  `response_result` text COLLATE utf8mb4_unicode_ci,
  `error_message` text COLLATE utf8mb4_unicode_ci,
  `ip_address` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_agent` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `duration_ms` int DEFAULT NULL,
  `create_time` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_operation_account_time` (`xianyu_account_id`,`create_time`),
  KEY `idx_operation_type_time` (`operation_type`,`create_time`),
  KEY `idx_operation_status_time` (`operation_status`,`create_time`),
  CONSTRAINT `fk_operation_account` FOREIGN KEY (`xianyu_account_id`) REFERENCES `xianyu_account` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_order_automation_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `xianyu_account_id` bigint NOT NULL,
  `order_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rate_status` tinyint NOT NULL DEFAULT '0' COMMENT '自动评价：0-未处理，1-成功，2-失败',
  `rate_time` datetime(3) DEFAULT NULL,
  `rate_error` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `red_flower_status` tinyint NOT NULL DEFAULT '0' COMMENT '求小红花：0-未处理，1-成功，2-失败',
  `red_flower_time` datetime(3) DEFAULT NULL,
  `red_flower_error` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `red_flower_attempt_count` int NOT NULL DEFAULT '0',
  `red_flower_next_retry_time` datetime(3) DEFAULT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_automation_account_order` (`xianyu_account_id`,`order_id`),
  KEY `idx_order_automation_red_flower` (`red_flower_status`,`red_flower_next_retry_time`),
  KEY `idx_order_automation_rate` (`rate_status`,`rate_time`),
  CONSTRAINT `fk_order_automation_account` FOREIGN KEY (`xianyu_account_id`) REFERENCES `xianyu_account` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_product_material` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `material_name` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `price` decimal(10,2) NOT NULL DEFAULT '0.00',
  `original_price` decimal(10,2) DEFAULT NULL,
  `quantity` int NOT NULL DEFAULT '1',
  `delivery_mode` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'FREE',
  `post_fee` decimal(10,2) DEFAULT NULL,
  `images_json` text COLLATE utf8mb4_unicode_ci,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_product_material_update_time` (`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `xianyu_sys_setting` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `setting_key` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `setting_value` text COLLATE utf8mb4_unicode_ci,
  `setting_desc` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_setting_key` (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
